[database]
url = "postgresql:///attic?host=/var/run/postgresql"

[storage]
type = "local"
path = "/mnt/nix-cache-store/attic/store"

[chunking]
nar-size-threshold = 8388608
min-size = 262144
avg-size = 1048576
max-size = 4194304

[compression]
type = "zstd"
